### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [HendrikBK/lewis-carroll_sylvie-and-bruno#1]
### General Issues:

- [x] The chapter files need `data-parent` attributes ([SEMOS 7.1.5.1](https://standardebooks.org/manual/1.7.3/single-page#7.1.5.1)).

- [x] The chapter titles need to use `<h3>` and `<p>` header levels ([SEMOS 7.2](https://standardebooks.org/manual/1.7.3/single-page#7.2)).

- [x] Remove `halftitlepage.xhtml`.

- [x] Remove `illustration-1.svg` from the `/images` folder.

- [x] Re-run `se typogrify .` and commit the changes.

- [x] Re-run `se semanticate .` and commit most of the changes.

- [x] Re-run `se modernize-spelling .` and commit most of the changes.

- [ ] Run `se build --check-only .` and fix the epubcheck errors.

### part-1.xhtml & part-2.xhtml:

- [x] Since a preface references the two parts as "Volume I" and "Volume II", these files should be renamed `volume-1.xhtml` and `volume-2.xhtml`; the file `<section>` elements should be `<section id="volume-1" epub:type="volume">` and `<section id="volume-2" epub:type="volume">.`

- [x] Change the titles to "Volume I" and "Volume II" respectively.

- [x] Each volume has an epigraph (files preface-1.xhtml and preface-3.xhtml). Move the epigraphs in to `volume-1.xhtml` and `volume-2.xhtml` files and structure them as epigraphs in section headers ([SEMOS 7.4.5](https://standardebooks.org/manual/1.7.3/single-page#7.4.5)).

### preface-2.xhtml:

- [x] Since this preface belongs to volume 1, the file should be renamed `volume-1-preface.xhtml`; the file semantics should be:
```
	<body epub:type="bodymatter z3998:fiction">
		<section data-parent="volume-1" id="volume-1-preface" epub:type="preface">
			<h3 epub:type="title">Preface</h3>
```

- [x] The `<i>` elements should be changed to `<em>`s.

- [x] For `<b>XLIX</b>`, move `<b>` and mark as a roman numeral.

- [x] Remove italics around `verbatim`, 

- [x] For the Latin poem, apply `xml:lang="la"` to the `<blockquote>` element instead.

- [x] You can combine the last two stanzas into a single `<blockquote epub:type="z3998:poem">`.

### preface-4.xhtml:

- [x] Since this preface belongs to volume 2, the file should be renamed `volume-2-preface.xhtml`; the file semantics should be:
```
	<body epub:type="bodymatter z3998:fiction">
		<section data-parent="volume-2" id="volume-2-preface" epub:type="preface">
			<h3 epub:type="title">Preface</h3>
```

- [x] Most `<i>` elements should be changed to `<em>`s.

- [x] In the first paragraph, mark the roman numeral in "Vol. I".

- [x] In `...we double the “r” in “preferred,”...`, mark `r` as a grapheme and remove the quotes ([SEMOS 8.2.8.2](https://standardebooks.org/manual/1.7.3/single-page#8.2.8.2)).

- [x] In `...by the etymology, to insert the double “l.”`, mark `l` as a grapheme and remove the quotes.

- [x] In `One was, to detect the 3 lines of “padding,”...`, spell out the number 3.

- [x] Remove periods in the table headers.

- [x] Tag `B.` as an abbreviation in `<a href="chapter-2-1.xhtml#chapter-2-1-p-10"><abbr epub:type="z3998:initialism">S.</abbr> and B. (<i>b</i>).</a>`.

- [x] For the second table, add `rowspan="10"` to `<td>Stanza</td>` and remove the empty `<td>` elements.

- [x] In the `<footer>`, remove `epub:type="se:letter.dateline"` and italics for Christmas.

### chapter-1-2.xhtml:

- [x] #2

- [x] Remove the `<i>` elements in the letter.

- [x] Omit the `<header>` element in the letter ([SEMOS 7.7.2.2](https://standardebooks.org/manual/1.7.3/single-page#7.7.2.2)).

### chapter-1-5.xhtml:

- [x] Remove italics and diacritic for `<em>viâ</em>`.

### chapter-1-9.xhtml:

- [x] Lowercase `<b>DAGGER</b>`.

### chapter-1-11.xhtml:

- [x] For `<b>I will lend him fifty pounds</b>`, replace `<b>` with `<strong>`.

- [x] For `<b><em>I will not charge you interest!</em></b>`, remove `<em>` and replace `<b>` with `<strong>`.

- [x] For `<b><em>I will lend you fifty more</em></b>`, remove `<em>` and replace `<b>` with `<strong>`.

### chapter-1-12.xhtml:

- [x] In the paragraph, `“It’s like this,” said the Other Professor, hastily drawing a long line upon the black board...`, mark the letters as graphemes.

### chapter-1-17.xhtml:

- [x]  You can combine stanzas into a single `<blockquote epub:type="z3998:poem">`.

### chapter-1-21.xhtml:

- [x] In `“And <b>God</b> meant your life to be so beautiful!”`, replace `<b>` with `<strong>`.

### chapter-1-22.xhtml:

- [x] Mark `<em>A</em>` and `<em>B</em>` as graphemes.

- [x] Lowercase `<b>FINIS</b>`.

### chapter-1-24.xhtml:

- [x] Correct the roman numeral in the title.

### chapter-2-1.xhtml:

- [x] For `<b>⁠E⁠—V⁠—I⁠—L</b>`, mark the individual letters with `z3998:grapheme` and hyphens between each letter ([SEMOS 8.2.8.2.1](https://standardebooks.org/manual/1.7.3/single-page#8.2.8.2.1)).

- [x] Lowercase `<b>LIVE</b>`.

### chapter-2-2.xhtml:

- [x] Mark `<em>A</em>` and `<em>B</em>` as graphemes.

### chapter-2-3.xhtml:

- [x] Mark the individual letters as graphemes.

### chapter-2-6.xhtml:

- [x] Lowercase `<b>DAIRY</b>`.

### chapter-2-10.xhtml:

- [x] Lowercase `<b>WINE</b>` and replace `<b>` with `<strong>`.

### chapter-2-15.xhtml:

- [x] Lowercase `<b>ROAR</b>` and replace `<b>` with `<strong>`.

### chapter-2-16.xhtml:

- [x] Sentence case `<b>NEVER</b>` and replace `<b>` with `<strong>`.

### chapter-2-18.xhtml:

- [x] For `<p>EXTRACT FROM THE “FAYFIELD CHRONICLE.”</p>`, place the tile in a `<header>` element and title case.

### chapter-2-19.xhtml:

- [x] Name case `ARTHUR FORESTER, M.D.`, place it in a `<b>` element, and mark `M.D.` as an abbreviation.

### chapter-2-24.xhtml:

- [x] Lowercase `<b>PRICKLY</b>` and replace `<b>` with `<strong>`.

### chapter-2-25.xhtml:

- [x] Sentence case `<b>ALL WILL LOVE SYLVIE</b>` and `<b>SYLVIE WILL LOVE ALL⁠—ALL WILL LOVE SYLVIE</b>`.

local.css:

- [x] Add the following CSS:
```
@namespace xml "http://www.w3.org/XML/1998/namespace";

blockquote[xml|lang]{
	font-style: italic;
}
```

- [x] Replace the table CSS with:
```
table{
	border: 1px solid;
	border-collapse: collapse;
	margin: 1em auto;
	text-align: center;
	vertical-align: top;
}

table td{
	vertical-align: top;
}

table th,
table:first-of-type td{
	border: 1px solid;
	text-align: center;
}

table:last-of-type tr + tr,
table:last-of-type td + td{
	border: none;
}
```

**Comment by EmmaSweeney** [comment]
### Lint Errors:

- [ ] c-015: You're missing some letter CSS. Copy and paste from the manual again, then remove unused CSS.

- [ ] s-007: In `chapter-2-18.xhtml`, `Extract From the “Fayfield Chronicle”` needs to also be in a `<p>` element.

- [ ] s-029: In the `data-parent` attribute, `Volume` needs to be lowercase like the file's id.

- [ ] s-034: In the volume files, change `epub:type="z3998:epigraph"` to `epub:type="epigraph"`.

- [ ] s-046: In the volume files, the epigraphs also need poem/song/verse semantics.

- [ ] s-71, s-077, & s-98: The volume title needs to be moved into the `<header>` element.

- [ ] f-015, s-029, x-017, x-019: The ids in your volume 2 chapters need to be `id="chapter-2-#"`.

- [ ] t-043: In `chapter-1-8.xhtml`, remove the italics around `apropos`.

### Epubcheck Errors:

- [ ] RSC-005: In `volume-2-preface.xhtml`, the tables' `<th>` elements need to be inside `<tr>` elements; remove `colspan="3"` from `<thead>` element.

### Issues:

- [ ] The volume titles need to be structured like in [SEMOS 7.2.9.1](https://standardebooks.org/manual/1.7.3/single-page#7.2.9.1).

- [ ] volume-2-preface.xhtml: In the first paragraph, mark the roman numeral in "Vol. I".

- [ ] volume-2-preface.xhtml: Use `<i>` elements for "(a)", "(b)", "(c)", etc.

- [ ] volume-2-preface.xhtml: the graphemes need to be italicized.

- [ ] chapter-1-22.xhtml: Replace `<em epub:type="z3998:grapheme">` with `<i epub:type="z3998:grapheme">`.

- [ ] chapter-2-1.xhtml: Replace `<b><span epub:type="z3998:grapheme">` with `<b epub:type="z3998:grapheme">`.

- [ ] chapter-2-3.xhtml: Remove `<em xml:lang="fr">` for `raison d’être`.
